- hosts: all
  become: yes
  tasks:
   - name: Start Machine Agent
     command: /opt/machine-agent/bin/machine-agent -d -p /opt/machine-agent/pidfile
   - name: Start tomcat
     service: name=tomcat state=restarted enabled=yes


