- hosts: datadomain
  become: no
  tasks:
   - name: Create Mtree
     shell: mtree create /data/col1/sample
   - name: Create CIFS Share
     shell: cifs share create sample path /data/col1/sample clients *
   
