- hosts: datadomain
  become: no
  tasks:
   - name: Create Mtree
     command: mtree create /data/col1/sample
   - name: Create CIFS Share
     command: cifs share create sample path /data/col1/sample clients *
   
